GP-2577 fix problem handling Elf32 missing sections / headers
The special flag for offset values (-1) wasn't being recognized in 32bit binaries, causing the ELF loader to try to read from index 4294967295, causing an exception:

java.io.IOException: Invalid index: 4294967295